name: 🐛 Bug Report
description: File a bug report
labels: [bug, no-bot]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue! :hugs:
        
        However note the following before opening an issue:
        :warning: **IF YOU DON'T FILL IN THE TEMPLATE, YOUR ISSUE IS LIABLE TO BE CLOSED.** :warning:

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I am able to reproduce the bug with the latest version"
          required: true
        - label: "I checked, but didn't find any duplicates (open OR closed) of this issue in the repo"
          required: true

  - type: input
    id: version
    attributes:
     label: Affected version
     description: "What version are you currently using?"
     placeholder: "x.y.z (check with the `packageVersion()` R function)"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the bug
      description: |
        Please add **ALL** the code necessary to reproduce the bug here (step-by-step).
        By 'reproduce', we mean that someone else can copy and paste the exact same code into their R console, execute it, and get the exact same output as you.
        
        This means you need to define all variables *within* the example, including data.
        You can upload a small sample of your data by dragging-and-dropping it into this Issue. 
        Alternatively, you can include code to create some dummy data that reproduces the error. 
        If that's not possible, please at least include a screenshot of your data and other relevant details.
        
        See [here](https://www.r-bloggers.com/2020/10/how-to-make-a-reprex/) for an intro to making a reproducible example (i.e. reprex) and why they're important! 
      placeholder: |
        # For example:
        df <- data.frame(list(a=rep(2,3), b=rep(1,3)))
        df["bTYPO"]
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Copy and paste the R console output. 
      placeholder: |
        # For example:
        Error in `[.data.frame`(df, "bTYPO") : undefined columns selected
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        Tell us what you expect to happen.
      placeholder: |
        The values of the data.frame column are printed.
    validations:
      required: true

  - type: textarea
    id: session-info
    validations:
      required: true
    attributes:
      label: Session info
      description: |
        Copy and paste the output of the `sessionInfo() R function.
      placeholder: |
        R version 4.4.1 (2024-06-14)  
        Platform: aarch64-apple-darwin20  
        Running under: macOS 15.0  
        
        Matrix products: default  
        BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib   
        LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0  
        
        locale:  
        [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8  
        
        time zone: Europe/London  
        tzcode source: internal 
        
        attached base packages:  
        [1] stats     graphics  grDevices utils     datasets  methods   base       
        ...
        ...
        ...
 
