name: ⭐ Feature Request
description: Submit a feature request
labels: [enhancement, no-bot]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a feature request! 
        
  - type: textarea
    id: the-feature-request
    attributes:
      label: The feature request
      description:
        Write a clear and concise description of what the feature or problem is.
      placeholder: |
        I think it could be improved by adding [...]
    validations:
      required: true
      
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Share how this will benefit its users.
      placeholder: |
        - One idea would be to add an [...], similar to how this package did [LINK].
        - An alternative solution might be [...]
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Please include any other context, like screenshots or mockups, if
        applicable.
      placeholder: |
        Our lab studies [...] and thought it would be cool to try [...]
