name: 'check-r'
description: >
  rworkflows: Run CRAN/Bioc checks and unit tests on an R package.
author: 'Brian M. Schilder' 
inputs: 
  i:
    description: >
      A list of inputs from the controller workflow.  
runs:
  using: 'composite'    
  steps:
    - name: Set GitHub token 
      run: |
        echo "GITHUB_PAT=${{ inputs.i.GITHUB_TOKEN }}" >> $GITHUB_ENV 
        echo "GITHUB_TOKEN=${{ inputs.i.GITHUB_TOKEN }}" >> $GITHUB_ENV 
      shell: bash {0}
     
    - name: Run CMD check
      env:
        _R_CHECK_CRAN_INCOMING_: false
        DISPLAY: 99.0
        AS_CRAN: ${{ inputs.i.run_crancheck }}
      run: |
        options(crayon.enabled = TRUE)
        if(!require("sessioninfo")) install.packages("rcmdcheck")
        as_cran <- if(Sys.getenv("AS_CRAN")=='true') "--as-cran" else NULL
        rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--timings", as_cran),
            build_args = c("--no-manual", "--keep-empty-dirs", "--no-resave-data"),
            error_on = "warning",
            check_dir = "check")
      shell: Rscript {0}
        
    - name: Reveal testthat details
      if: ${{ inputs.i.has_testthat }} == 'true'
      run: |
        find . -name testthat.Rout -exec cat '{}' ';'
      shell: bash {0}
        
    - name: Run RUnit tests
      if: ${{ inputs.i.has_runit }} == 'true'
      run: |
        options(crayon.enabled = TRUE)
        BiocGenerics:::testPackage()
      shell: Rscript {0}
        
    - name: Run BiocCheck
      if: ${{ inputs.i.run_bioccheck }} == 'true'
      env:
        DISPLAY: 99.0
      run: |
        options(crayon.enabled = TRUE)
        if(!require("BiocManager")) install.packages("BiocManager")
        if(!require("BiocCheck")) BiocManager::install("BiocCheck")
        BiocCheck::BiocCheck(
            dir('check', 'tar.gz$', full.names = TRUE),
            `quit-with-status` = TRUE,
            `no-check-R-ver` = TRUE,
            `no-check-bioc-help` = TRUE)
      shell: Rscript {0}
        
    - name: Test coverage
      if: inputs.i.runner_os == 'Linux'
      uses: codecov/codecov-action@v3 

    - name: Upload check results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: inputs.i.runner_os-biocversion-${{ matrix.config.bioc }}-r-${{  matrix.config.r }}-results
        path: check
        
